Lower-resolution avatars
mlemgroup/mlem pull request #1112
Opened 2024-06-25 19:28 UTC by Sjmarf

2024-06-26 19:16 UTC, EricBAndrews requested changes
Looks good, small question

2024-06-26 19:16 UTC, EricBAndrews commented on Mlem/App/Views/Shared/Avatar/AvatarView.swift
> +                VStack {
Why `VStack`?

2024-06-26 19:58 UTC, Sjmarf commented on Mlem/App/Views/Shared/Avatar/AvatarView.swift
> +                VStack {
Not needed; I removed it 👍

2024-06-29 04:21 UTC, EricBAndrews approved these changes
LGTM 👍

2024-06-29 07:27 UTC, merged