Expanded Post comment resolution
mlemgroup/mlem pull request #1141
Opened 2024-07-13 11:01 UTC by Sjmarf

> [!note]
> Built on-top of #1134; drafting until that's in.

## `FeedsView`

Changed the "Reload on Switch" settings toggle to this picker:

<img src="https://github.com/user-attachments/assets/c09728c7-95b8-41ba-bcda-9a724ee33a6b" width=40%>

"Refresh App" is the default setting.

If "Refresh Feeds Only" is selected, feeds will be immediately refreshed when the account changes.

If "Don't Refresh" is selected, feeds will not be refreshed. Instead, a small popup will be shown on feed pages prompting the user to refresh.

## `ExpandedPostView`

`ExpandedPostView` will now immediately attempt to resolve if the post it is instantiated with doesn't match the active `ApiClient`.

`ExpandedPostView` will also now resolve comments when the account is switched. It does this by fetching the post's comments from the new API, then modifying the `CommentWrapper` tree to replace old comments with new ones. 

Sometimes, a comment will be present on one API but not on another. If the comment was present on the old API but not on the new one, the old comment will remain in the tree but will not be able to be interacted with. I think this is a better alternative than removing those comments, which would cause the feed to jump. If a comment is present on the new API but not the old one, the new comments will be inserted into the feed - this _will_ cause the feed to jump, but I don't see a better alternative.

2024-07-21 17:07 UTC, EricBAndrews requested changes
Looking good--something's a little funky with the re-resolution, though. If I open a post in a guest account and switch to an authenticated account, the post doesn't re-resolve (or at least, isn't interactable) until I switch tabs and switch back again.

2024-07-21 17:07 UTC, EricBAndrews commented on Mlem/App/Views/Shared/ExpandedPostView.swift
> +    // @ViewBuilder
Dead code?

2024-07-22 12:20 UTC, Sjmarf commented
Hmm, I'm struggling to reproduce the issue 🤔 Does it happen every time you do that, on every post?

2024-07-22 19:20 UTC, EricBAndrews commented
I tested this a bit more thoroughly--it's limited to when the guest account and the main account are on the same instance, which makes me think the issue is that `ExpandedPostView:50` isn't detecting the switch from an unauthenticated to an authenticated account within the same instance. Everything works fine when going from guest on one instance to user on another.

2024-07-22 21:12 UTC, Sjmarf commented
Thanks, that was the issue! Fixed 👍

2024-07-23 18:03 UTC, EricBAndrews approved these changes
LGTM 👍

2024-07-23 19:37 UTC, merged