Reply Sheet UI
mlemgroup/mlem pull request #1144
Opened 2024-07-15 20:54 UTC by Sjmarf

> [!note] 
> Built on-top of #1134; drafting until that's in

Added a non-functional reply sheet UI for posts (not comments yet). It includes a basic markdown editor, with all of the inline markdown elements and spoilers implemented. Later on, I'll add buttons for quote blocks, bulleted lists, numbered lists, headings, image uploading etc.

 In v1, you could swipe the sheet down to a lower detent so that you can interact with the content behind it. I've re-implemented this here, but the sheet goes much further down this time:
 
<img src="https://github.com/user-attachments/assets/3ca7a5e7-4d66-4fc4-9cd2-425b455f05ad" width=50%>

This will only happen if you swipe down whilst the text-editor is non-empty. Otherwise, the sheet will be closed.

2024-07-25 21:08 UTC, EricBAndrews requested changes
Really impressive work!

I've found a couple little defects:

- Selecting text, then making it bold, then italic results in the text being simply italic (it looks like the italic detector picks up the outer \*s and un-italics it). Going italic -> bold works as expected.
- Text past the third line vanishes into limbo along with the cursor--I think it goes off to the right of the screen, but it's hard to tell.

2024-07-25 21:08 UTC, EricBAndrews commented on Mlem.xcodeproj/project.pbxproj
> +				kind = branch;
Reminder

2024-07-25 21:08 UTC, EricBAndrews commented on Mlem/App/Views/Pages/ResponseComposerView.swift
> +                    .padding(.vertical, 10)
```suggestion
                    .padding(.vertical, AppConstants.standardSpacing)
```

2024-07-25 21:08 UTC, EricBAndrews commented on Mlem/App/Views/Shared/MarkdownEditorToolbarView.swift
> +                }
*nit*

System image names should go in `Icons`, there's an off chance we'll want them elsewhere

2024-07-25 21:08 UTC, EricBAndrews commented on Mlem/App/Views/Shared/MarkdownTextEditor.swift
> +        // textView.setContentHuggingPriority(.defaultLow, for: .vertical)
*nit*

Dead code?

2024-07-25 21:08 UTC, EricBAndrews commented on Mlem/App/Views/Shared/MarkdownTextEditor.swift
> +        textView.textContainerInset = .init(top: 5, left: 10, bottom: 10, right: 10)
*nit*

```suggestion
        textView.textContainerInset = .init(top: AppConstants.halfSpacing, left: AppConstants.standardSpacing, bottom: AppConstants.standardSpacing, right: AppConstants.standardSpacing)
```

2024-07-25 22:52 UTC, Sjmarf commented
> Selecting text, then making it bold, then italic results in the text being simply italic (it looks like the italic detector picks up the outer *s and un-italics it). Going italic -> bold works as expected.

Nice catch. My "solution" to this is to make italics use the alternative "_" instead of "*". I think this is cleaner anyways, and it's what GitHub uses. This issue also exists with strike-through ("~~") and subscript ("~"), though that is a much less used combination. Fixing this properly is possible, but considering that people won't run into it often I think it's safe to leave it for now. I've opened an issue [here](https://github.com/mlemgroup/mlem/issues/1158) to keep track of this.

> Text past the third line vanishes into limbo along with the cursor--I think it goes off to the right of the screen, but it's hard to tell.

Fixed 👍

2024-07-31 14:24 UTC, EricBAndrews approved these changes
LGTM!

Sorry this review took so long, my cat chewed through my charging cable and I couldn't test on-device lmao

2024-07-31 15:20 UTC, Sjmarf commented
No worries xD

2024-07-31 15:20 UTC, merged