New App Icons
mlemgroup/mlem pull request #1179
Opened 2024-07-31 17:28 UTC by Sjmarf

- Added dark variants of each icon
- Removed clay/s icons
- Added pride icon

Because each app icon asset now contains three images, using `UIImage(named: )` to get the images no longer works. I spent a while trying to fix this, but couldn't work it out. I'll try again before v2.0 release - worst-case scenario, I can just add duplicate (lower-resolution) images of each icon to the asset catalogue and use those. I've opened an issue [here](https://github.com/mlemgroup/mlem/issues/1178) to keep track of this.

2024-08-03 03:06 UTC, EricBAndrews requested changes
It looks like some files got missed in the commit--I'm getting "build input files not found" on the whole `.../Settings/Icon` tree, and they're not showing up in Finder:

<img width="1368" alt="Screenshot 2024-08-02 at 11 01 58 PM" src="https://github.com/user-attachments/assets/6e395d9f-eaf5-4a15-a4b6-c80c6fc762e8">

2024-08-03 03:06 UTC, EricBAndrews commented on Mlem/App/Utility/Extensions/Bundle+Extensions.swift
> +//  Bundle+IconFileName.swift
*nit*
```suggestion
//  Bundle+Extensions.swift
```

2024-08-03 03:06 UTC, EricBAndrews commented on Mlem/App/Views/Shared/CollapsibleSection.swift
> +                Color(uiColor: .systemGroupedBackground)
*nit*
```suggestion
                palette.groupedBackground
```

2024-08-03 03:06 UTC, EricBAndrews commented on Mlem/App/Views/Shared/CollapsibleSection.swift
> +                        .foregroundStyle(.secondary)
*nit*
```suggestion
                        .foregroundStyle(palette.secondary)
```

2024-08-03 03:06 UTC, EricBAndrews commented on Mlem/App/Views/Shared/CollapsibleSection.swift
> +        .background(Color(uiColor: .secondarySystemGroupedBackground))
*nit*
```suggestion
        .background(palette.groupedBackground))
```

2024-08-03 10:21 UTC, Sjmarf commented
`Icon` was gitignored 🤔 I've fixed it 👍

2024-08-04 00:51 UTC, EricBAndrews requested changes
Code looks good, and the new dark app icons are lovely!

I've noticed a couple problems:
- App icon is always the dark variant, regardless of phone light/dark mode--I'm also seeing "The app icon set <icon set> has 2 unassigned children" warnings on all icon sets, which is likely the cause
- Changing the icon works, but doesn't update the selector:

https://github.com/user-attachments/assets/ab989c27-966c-4754-afc7-f7474a222984

2024-08-04 12:51 UTC, Sjmarf commented
It seems Xcode 15 isn't able to build the new icon files correctly. It only builds the first image in each asset (alphabetically). I've renamed the light-theme images to `aaa.png`, which causes them to take priority over the dark variants. The icons will only change with the theme if the app is built on Xcode 16.

2024-08-04 16:52 UTC, EricBAndrews approved these changes
LGTM 👍 

The Xcode 15 icons behavior isn't ideal since that's the current production build system, but 16 releases in a month so it's probably fine.

2024-08-04 18:53 UTC, merged