Working post replies
mlemgroup/mlem pull request #1184
Opened 2024-08-04 15:04 UTC by Sjmarf

Replying to posts is now functional. You can choose which account to reply from using the drop-down at the top. This necessitated moving the `ExpandedPost+Logic` stuff into a dedicated `ExpandedPostTracker` class. None of that logic has actually changed.

2024-08-07 02:00 UTC, EricBAndrews requested changes

2024-08-07 02:00 UTC, EricBAndrews commented on Mlem/App/Utility/Extensions/ApiClient+Extensions.swift
> +    var isAuthenticatedAndActive: Bool { isActive && token != nil }
*nit*

Super useful construct, but the name is a mouthful--maybe `canInteract` is a little more ergonomic?

2024-08-07 02:00 UTC, EricBAndrews commented on Mlem/App/Views/Shared/Images/SimpleAvatarView.swift
> +//
Is this intentionally re-introduced?

2024-08-07 02:00 UTC, EricBAndrews commented on Mlem/App/Views/Pages/ResponseComposerView.swift
> +        self.expandedPostTracker = expandedPostTracker
This line fails the build on Xcode 15

```suggestion
        self.originalContext = context
        self._resolvedContext = .init(wrappedValue: context)
        self.expandedPostTracker = expandedPostTracker
```

2024-08-07 02:00 UTC, EricBAndrews commented on Mlem/App/Views/Shared/MarkdownTextEditor.swift
> +        text = textView.text
Not sure if it's this line specifically that's responsible, but I get the following concurrency error when opening the reply sheet, flagged on L11:

`Modifying state during view update, this will cause undefined behavior.`

2024-08-07 02:00 UTC, EricBAndrews commented on Mlem/App/Views/Pages/ResponseComposerView.swift
> +    func send() async {
In my testing, I found the reply was always sent from the account that was active when the sheet was first opened.

2024-08-07 09:39 UTC, Sjmarf commented on Mlem/App/Views/Shared/Images/SimpleAvatarView.swift
> +//
Yes - `.clipShape` doesn't work in for images a context menu; this view crops the image itself rather than using `.clipShape`.

2024-08-07 09:49 UTC, Sjmarf commented on Mlem/App/Utility/Extensions/ApiClient+Extensions.swift
> +    var isAuthenticatedAndActive: Bool { isActive && token != nil }
Sure 👍

2024-08-07 09:49 UTC, Sjmarf commented on Mlem/App/Views/Shared/MarkdownTextEditor.swift
> +        text = textView.text
Fixed 👍

2024-08-07 09:55 UTC, Sjmarf commented on Mlem/App/Views/Pages/ResponseComposerView.swift
> +    func send() async {
Hmm, I can't reproduce this behavior on iOS 17.5 or iOS 18. To be clear, changing the account from the drop-down at the top doesn't change the global "active" account - it just chooses which account that reply is posted from. What iOS version are you using?

2024-08-07 14:57 UTC, EricBAndrews commented on Mlem/App/Views/Pages/ResponseComposerView.swift
> +    func send() async {
iOS 17 simulator. Also tested with accounts on real instances and differing instances:


https://github.com/user-attachments/assets/f184bed7-d173-49e5-875c-0b599648028e

2024-08-07 17:12 UTC, Sjmarf commented on Mlem/App/Views/Pages/ResponseComposerView.swift
> +    func send() async {
Thanks! I was able to reproduce this on a local instance and I think I've fixed it.

2024-08-08 15:26 UTC, EricBAndrews approved these changes
LGTM! 🔥 

The user switching UI is really clean!

2024-08-08 17:16 UTC, merged