Image resolution
mlemgroup/mlem pull request #1204
Opened 2024-08-11 16:51 UTC by Sjmarf

Images are now fetched at a lower resolution. This mitigates lag caused by the feed having super high-res images (such as in c/pics). The resolution is dependent on the post size setting.

The downside of doing this is that it can take a second or so for a higher-res image to load in when you open the expanded post or the image viewer. This is most noticeable in compact/headline modes, where images are initially fetched at a much lower resolution of 256px. I guess one way to fix this would be to fetch images at 1024px for _all_ post sizes, not just Large? Do you think it would be better that way?

Closes #1203

2024-08-13 20:00 UTC, EricBAndrews requested changes
Code looks good! I've noticed a couple of things:

1. The image viewer is _significantly_ slower to appear on large images (~.5s to the beginning of the animation, ~1s to fully open compared to previous ~.25s/.75s). You can see the difference side-by-side:

https://github.com/user-attachments/assets/eef13c54-7006-41ab-af1b-6a9e53709828 

https://github.com/user-attachments/assets/7b60f46c-bbcb-4f7e-ae09-6600350b794e

It looks like the issue is that SwiftUI wants to render the `DynamicImageView` before the sheet starts opening, which takes a moment on big images. I was able to replicate the original performance by using this code:

```
    @State var appeared: Bool = false

    ...

        if appeared {
            ZoomableContainer {
                DynamicImageView(url: url)
                    .padding(Constants.main.standardSpacing)
            }
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    CloseButtonView()
                }
            }
        } else {
            ProgressView()
                .onAppear {
                    DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
                        appeared = true
                    }
                }
        }
```

2. Thumbnail images sometimes don't pick up loading state change until they disappear and reappear (tested on both Compact and Headline post size, larger sizes do not seem to be affected):

https://github.com/user-attachments/assets/48dd9eee-86f8-423d-ad11-8f8effaef5d9

2024-08-13 20:00 UTC, EricBAndrews commented on Mlem.xcodeproj/project.pbxproj
> +				kind = branch;
Reminder

2024-08-15 20:53 UTC, Sjmarf commented
> The image viewer is significantly slower to appear on large images

This isn't new behavior I don't think - I can also reproduce this on super-large images on dev2:

https://github.com/user-attachments/assets/684af395-5918-4936-a3a1-6134ec8e3a34

I don't _think_ it's any worse in this PR, and I can't find a (good) way to fix it at the moment. Are you happy for me to leave this as OOS? I'll open an issue for it.

> Thumbnail images sometimes don't pick up loading state change until they disappear and reappear

Fixed (I think) 👍

2024-08-16 22:44 UTC, EricBAndrews approved these changes
I'm content to leave image viewer appearance time OOS for this PR.

One small build failure--trivial enough not to be worth a re-review cycle.

2024-08-16 22:44 UTC, EricBAndrews commented on Mlem/App/Utility/Extensions/Content Models/DeletableProviding+Extensions.swift
> +                let result = await task.result.get()
This change causes build failure on Xcode 15.4--I'm not entirely sure why it built for me last review, but I can't get it to build now even on a totally clean clone

```suggestion
                let result = try await task.result.get()
```

2024-08-17 16:03 UTC, merged