Reporting
mlemgroup/mlem pull request #1206
Opened 2024-08-12 13:17 UTC by Sjmarf

> [!note]
> Built ontop of #1199, drafting until that's in.

Implemented reporting. The report sheet shows a list of community and instance rules. You can tap on one to auto-fill the "reason" box. I also included the "Spam", "Troll" and "Abuse" buttons for convenience, similar to the v1.0 post removal sheet.

<img src="https://github.com/user-attachments/assets/8428101a-96a2-4c82-b2ef-d5c65146a323" width=50%>

2024-08-12 19:21 UTC, Sjmarf commented
Closes #1205

2024-08-14 13:55 UTC, EricBAndrews requested changes
I found a couple minor build issues, other than those looks good! Nice work on the rules section, that's super clean 😁

2024-08-14 13:55 UTC, EricBAndrews commented on Mlem/App/Utility/Extensions/Content Models/ReportableProviding+Extensions.swift
> +            callback: true ? { self.showReportSheet(communityContext: communityContext) } : nil
*nit*

Ternary unnecessary since condition always `true`

```suggestion
            callback: { self.showReportSheet(communityContext: communityContext) }
```

2024-08-14 13:55 UTC, EricBAndrews commented on Mlem/App/Views/Pages/ReportComposerView.swift
> +            HapticManager.main.play(haptic: .success, priority: .low)
Build failure on Xcode 15.4

```suggestion
            await HapticManager.main.play(haptic: .success, priority: .low)
```

2024-08-14 15:04 UTC, EricBAndrews approved these changes
LGTM! 🔥

2024-08-14 15:05 UTC, merged