Codable Settings
mlemgroup/mlem pull request #1312
Opened 2024-09-08 18:58 UTC by EricBAndrews

# Checklist
- [x] I have read CONTRIBUTING.md
- [x] I have described what this PR contains
- [x] If this PR alters the UI, I have attached pictures/videos
- [x] This PR addresses one or more open issues that were assigned to me:
      - closes #1298 
      - closes #1268 

# Pull Request Information

This PR makes `Settings` codable. This is accomplished through the intermediate `CodableSettings` struct; `Settings` cannot be made directly because doing so results in `AppStorage` values being updated every time any `Settings` object is decoded. `CodableSettings` ultimately should replace `Settings` entirely, migrating our settings storage from `AppStorage` to JSON, but that's OOS here.

Some logic has been added to `PersistenceRepository` to save and retrieve settings files. There are two different locations settings files are stored:
- System: these are app-generated settings files used for migration and persistence. From the code, they are identified by the `SystemSetting` enum.
- User: these are user-generated settings files. Currently this system is not used, but the idea is to offer easily configurable and swappable settings profiles. These can then optionally be attached to accounts.

The new codable settings enable the following features:

- Migrate from V1 settings: I'll have a PR up soon against v1 that saves those settings to a `CodableSettings` JSON. 
- Save/Restore settings: "Save settings" saves the current settings state to System/v2. "Restore settings" reverts settings to that configuration.
- Import/Export settings: allows users to directly import and export settings JSON files.

2024-09-12 15:16 UTC, Sjmarf requested changes
Nice work!

We aren't currently tracking interaction bar configurations here - I think we should.

2024-09-12 15:16 UTC, Sjmarf commented on Mlem/App/Views/Root/Tabs/Settings/ImportExportSettingsPage.swift
> +// DO NOT use Picker in this page! It refuses to change the theme until it gets re-rendered. All other components pick up theme changes correctly.
I've noticed the text color in comments failing to pick up theme changes on occasion too, though every time I try to reproduce it I can't xD

2024-09-12 15:16 UTC, Sjmarf commented on Mlem/App/Globals/Definitions/PersistenceRepository.swift
> +    case v_1, v_2
*nit* Maybe `case v1, v2` is better?

2024-09-13 22:27 UTC, EricBAndrews commented
Opened #1323 to handle widget persistence

2024-09-14 08:36 UTC, Sjmarf approved these changes
LGTM 💯

2024-09-14 17:02 UTC, merged