Bubbly app design
mlemgroup/mlem pull request #1326
Opened 2024-09-15 21:26 UTC by Sjmarf

Drafting for now - still need to work out some transitions

2024-09-16 20:29 UTC, Sjmarf commented
I've commented out the fancy transition code for now, as it requires Xcode 16 and we can't upgrade to Xcode 16 until #1183 is fixed.

2024-09-18 22:09 UTC, EricBAndrews requested changes
Really nice work! Makes the app feel much more modern.

A couple notes, plus Slack discussion

2024-09-18 22:09 UTC, EricBAndrews commented on Mlem/App/Views/Pages/Community/CommunityView.swift
> +                    .background(palette.secondaryGroupedBackground, in: .rect(cornerRadius: 10))
We should standardize corner radii, since we're suddenly using them a _lot_. Generally we have corner radius = spacing, which is convenient and also aesthetically pleasing--we could roll it into `standardSpacing`

2024-09-18 22:09 UTC, EricBAndrews commented on Mlem/App/Views/Pages/Person/PersonView.swift
I'm not sure where the precise culprit is but a little bit of padding got added that mucks up the tile layout:

<img width="387" alt="Screenshot 2024-09-18 at 6 01 19 PM" src="https://github.com/user-attachments/assets/71cefbec-5f90-43c8-bec6-52b3fd9dc49f">

2024-09-18 22:34 UTC, Sjmarf commented on Mlem/App/Views/Pages/Person/PersonView.swift
Nice catch 👍

2024-09-18 22:35 UTC, Sjmarf commented on Mlem/App/Views/Pages/Community/CommunityView.swift
> +                    .background(palette.secondaryGroupedBackground, in: .rect(cornerRadius: 10))
Sure, makes sense 👍

2024-09-19 22:14 UTC, EricBAndrews approved these changes
LGTM! 🔥

2024-09-19 22:40 UTC, merged