`CommentPage`
mlemgroup/mlem pull request #1367
Opened 2024-09-29 14:25 UTC by Sjmarf

Adds this view:

<img src="https://github.com/user-attachments/assets/5b893abd-3397-4236-8c96-0ff7e6ee4e23" width=50%>

In this PR, the menu is shown anytime a comment is navigated to. What do you think about that? Are there some cases where the old behavior would be better? Theoretically this is safer than the old behaviour, because it guarantees that the comment is loaded in the comment list (the old method did not). Though, that doesn't happen particularly frequently and could be worked around by sending a second API request. The one case where we _must_ display this view is when a comment chain gets so deep that the comments become too thin.

I've also added the "Load more comments" buttons when the comments aren't initially loaded.

<img src="https://github.com/user-attachments/assets/d8b36429-3e17-4d28-b09e-40f3feaab9a8" width=50%>

Here's some posts where the "Load more" button is shown:

https://lemmings.world/post/405439
https://lemmy.ml/post/13565023

2024-09-29 22:20 UTC, Sjmarf commented
Also closes #1366

2024-09-30 22:18 UTC, EricBAndrews requested changes
Code looks good!

Some design notes:

- "More Replies" can be the same font size as a comment, and maybe wants to be `.accent` to indicate that it's a button
<img width="392" alt="Screenshot 2024-09-30 at 6 05 11 PM" src="https://github.com/user-attachments/assets/a8510ae1-e10b-41e0-a8d2-12a454167bc6">
- Selecting "View All" after navigating into `CommentPage` from `ExpandedPostView` should take you back rather than pushing a new `ExpandedPostView`
- The highlight on the navigated-to comment should fade after a moment
- The "View All"/"View Parent" buttons feel a bit heavy, though I'm not sure what a nice way to lighten them would be

Also, maybe OOS for this PR, but `CommentTreeTracker` L150 should be `@MainActor`--got a crash on that line while testing

2024-09-30 22:18 UTC, EricBAndrews commented on Mlem/App/Views/Shared/ExpandedPost/ExpandedPostView.swift
> +                            .foregroundStyle(.secondary)
*nit*

Or `.accent` (see general comment)

```suggestion
                            .foregroundStyle(palette.secondary)
```

2024-10-01 10:36 UTC, Sjmarf commented
> The "View All"/"View Parent" buttons feel a bit heavy, though I'm not sure what a nice way to lighten them would be

Maybe like this?

<img src="https://github.com/user-attachments/assets/8907935b-3c9b-49e3-9819-528c162d6707" width=50%>

> Selecting "View All" after navigating into `CommentPage` from `ExpandedPostView` should take you back rather than pushing a new `ExpandedPostView`

What about just hiding the "View All" button in that context? Making it go back feels weird to me - there's already a back button in the top-left of the screen

2024-10-01 22:30 UTC, EricBAndrews approved these changes
LGTM! 🚀

2024-10-01 22:38 UTC, merged