Remove Content
mlemgroup/mlem pull request #1381
Opened 2024-10-10 14:09 UTC by Sjmarf

Allows moderators to remove posts and comments. Relies on [this MlemMiddleware PR](https://github.com/mlemgroup/MlemMiddleware/pull/66).

2024-10-11 20:16 UTC, EricBAndrews requested changes
Code looks good!

It's a little strange to have "Spam"/"Troll"/"Abuse" options for restoring posts--we should either disable them or offer alternatives ("Accident" would be one, others aren't jumping to mind right now)

2024-10-11 20:16 UTC, EricBAndrews commented on Mlem.xcodeproj/project.pbxproj
> +				kind = branch;
Reminder

2024-10-11 20:16 UTC, EricBAndrews commented on Mlem/App/Views/Shared/CommentView.swift
> +//                            EllipsisMenu(size: 24) { comment.menuActions(commentTreeTracker: commentTreeTracker) }
*nit*

Dead code?

2024-10-12 14:03 UTC, Sjmarf commented
Makes sense; I've removed the reason shortcuts on the restore sheet 👍

2024-10-12 23:26 UTC, EricBAndrews approved these changes
LGTM! 🚀

2024-10-13 12:56 UTC, merged