Actor Feed Loaders
mlemgroup/mlem pull request #1434
Opened 2024-11-13 23:31 UTC by EricBAndrews

Frontend changes for [the real PR](https://github.com/mlemgroup/MlemMiddleware/pull/70).

Contains two minor changes of note:
- `EndOfFeedView` can now take in an optional `loadMore` callback; if available, a "Load More" button will be rendered at the bottom of the feed if the `loadingState` is `idle`. Sometimes hiding read posts creates a feed that won't trigger the infinite load; this handles that case without needing to do weird threshold hacks. This will also make implementing #832 trivial.
- `loadFeed` now triggers if the loader is empty regardless of `loadingState`. The middleware PR changes the initial `loadingState` to be `.loading`, which in turn results in a spinner being immediately rendered when an empty feed is opened.

2024-11-15 11:57 UTC, Sjmarf requested changes

2024-11-15 11:57 UTC, Sjmarf commented on Mlem.xcodeproj/project.pbxproj
> +				branch = "eric/actor-feed-loaders";
Reminder

2024-11-15 11:57 UTC, Sjmarf commented on Mlem/App/Views/Shared/Search/SearchView.swift
There's a couple of bugs related to post searching in this PR:

1) Changing any of the post filters doesn't refresh the post feed. Possibly missing `@Observable` somewhere in MlemMiddleware?
2) With the search bar unfocused, tapping on the "Posts" tab in Search loads the results for the search query `""`. Before this PR, it would wait until the user submits their search query before loading anything.

2024-11-15 11:57 UTC, Sjmarf commented on Mlem/App/Views/Shared/PersonContentGridView.swift
In the saved feed, switching account without reloading and then tapping the "refresh" button loads the previous account's saved content rather than the saved content of the new account.

2024-11-15 21:17 UTC, EricBAndrews commented on Mlem/App/Views/Shared/PersonContentGridView.swift
Nice catch! I've implemented some custom refresh logic for `PersonContentFeedLoader` that should fix this.

2024-11-15 21:40 UTC, EricBAndrews commented on Mlem/App/Views/Shared/Search/SearchView.swift
(2) was due to the change in default loading state causing that first load--I've changed that behavior for the `SearchPostFeedLoader` on the middleware PR. I could only repro (1) using the erroneous load from (2)--the filters trigger refreshes properly for me when using a real search.

2024-11-16 00:11 UTC, Sjmarf commented on Mlem/App/Views/Shared/Search/SearchView.swift
Yep, it looks like it was only broken for that first erroneous load 👍

2024-11-16 00:11 UTC, Sjmarf approved these changes
LGTM! Closes #1402 😄

2024-11-16 00:17 UTC, Sjmarf requested changes
Hmm I might have found another bug actually

2024-11-16 02:59 UTC, EricBAndrews commented
> Maybe it's related to having < pageSize items in the first page of results?

Yep, that was it--forgot to return the undersized page instead of the default empty array when I made that change lol

2024-11-16 16:49 UTC, Sjmarf approved these changes
LGTM 👍

2024-11-16 18:28 UTC, merged