Fix community account switch behavior
mlemgroup/mlem pull request #1443
Opened 2024-11-17 23:54 UTC by EricBAndrews

>[!NOTE]
>Depends on [this PR](https://github.com/mlemgroup/MlemMiddleware/pull/73)

# Checklist
- [x] I have read CONTRIBUTING.md
- [x] I have described what this PR contains
- [x] If this PR alters the UI, I have attached pictures/videos
- [x] This PR addresses one or more open issues that were assigned to me:
      - closes #1442

# Pull Request Information

Fixes an issue where the outdated feed popup didn't work in communities.

- Changing `feedLoader` API is now handled in `outdatedFeedPopup`
- Communities will not show the outdated feed popup if they are in guest mode

2024-11-18 11:05 UTC, Sjmarf requested changes
Code looks good! Found a couple of bugs:

1) When using a lemmy.world guest, tapping "reload" in a `CommunityView` causes the popup to immediately appear again.
2) Previously the outdated feed popup would slide in and out - now it just appears, with no animation. The animation still works fine in `PersonView`, but not in `CommunityView` or the feed.

2024-11-18 11:05 UTC, Sjmarf commented on Mlem.xcodeproj/project.pbxproj
> +				CDE1816C2CEAA4E6001D7492 /* XCLocalSwiftPackageReference "../MlemMiddleware" */,
Reminder

2024-11-18 17:54 UTC, EricBAndrews commented
> Previously the outdated feed popup would slide in and out - now it just appears, with no animation. The animation still works fine in PersonView, but not in CommunityView or the feed.

This was kinda tricky! The cause was the added check in `CommunityView` to avoid presenting the popup on unresolvable communities--this was causing the _outer_ `if canShowPopup` to toggle the entire popup view, bypassing the animation. `canShowPopup` is now simply factored into the `showRefreshPopup` logic.

2024-11-19 12:20 UTC, Sjmarf approved these changes
LGTM 💯

2024-11-19 16:21 UTC, merged