Rounded Post/Comment Editor Design
mlemgroup/mlem pull request #1446
Opened 2024-11-25 11:21 UTC by Sjmarf

2024-11-26 22:39 UTC, EricBAndrews requested changes
Code looks good!

I see this when I open the post composer:

![IMG_EE1698E64C44-1](https://github.com/user-attachments/assets/9f5d8d2f-23b6-40ae-9bf0-1acf3fd335b9)

2024-11-26 22:39 UTC, EricBAndrews commented on Mlem/App/Views/Pages/PostEditor/PostEditorView+Logic.swift
> +        print(lastFocusedField)
*nit*

Still needed?

2024-11-28 10:34 UTC, Sjmarf commented
Nice catch, fixed 👍 Strangely this issue didn't happen on my physical device, but I could reproduce it on a simulator.

2024-11-29 22:25 UTC, EricBAndrews approved these changes
LGTM! 🚀

2024-11-30 21:46 UTC, merged