Eric/inbox feed loader
mlemgroup/mlem pull request #1478
Opened 2024-12-06 01:35 UTC by EricBAndrews

# Checklist
- [x] I have read CONTRIBUTING.md
- [x] I have described what this PR contains
- [x] If this PR alters the UI, I have attached pictures/videos
- [x] This PR addresses one or more open issues that were assigned to me:
      - closes #1432 

# Pull Request Information

Frontend changes for https://github.com/mlemgroup/MlemMiddleware/pull/74.

Mostly just updates to use `InboxFeedLoader` and friends. The main notable change is that items are not all hidden when "mark all as read" is used. This is consistent with how the feed behaves when read items are filtered out and the user marks an item as read (i.e., it remains visible)

This PR also includes a minor tweak to show the media type indicator when developer mode is active, rather than guarding it in `#DEBUG`. This should make daily driving a local dev build nicer, plus offer that insight in the production app as well if needed.

2024-12-07 14:39 UTC, Sjmarf commented
The inbox doesn't respect the "Infinite scroll" setting - is this intentional?  Also, the "Load more" button flashes briefly when loading a new page, which isn't ideal.

This PR closes #1479 💯

2024-12-07 19:20 UTC, Sjmarf requested changes
Found a few bugs:
- The "inbox is outdated" popup isn't shown anymore when the tab badge count changes.
- The "Load more" button flashes briefly when loading a new page.
- The inbox doesn't respect the "Infinite scroll" setting - is this intentional? 

This PR closes #1479 💯

2024-12-08 17:43 UTC, EricBAndrews commented
> The inbox doesn't respect the "Infinite scroll" setting - is this intentional?

Yes. The theory is that manual page loading is a time management tool, but since people don't really "scroll" their inbox like they do a feed it doesn't make sense in that context.

2024-12-08 18:04 UTC, EricBAndrews commented
> The "Load more" button flashes briefly when loading a new page.

This one was a middleware issue--fixed [here](https://github.com/mlemgroup/MlemMiddleware/pull/74/commits/a57a794b3b3678073fc70416785184745d697aaa). It was a super trivial change (just needed to move the loading state assignment to after the item assignment), so I went ahead and merged the middleware side--if there are other issues that need a middleware fix I'll open a new one

2024-12-08 18:22 UTC, Sjmarf approved these changes
LGTM! 👍

2024-12-08 18:22 UTC, Sjmarf commented on Mlem/App/Views/Shared/EndOfFeedView.swift
> +                        Text("IDLE")
```suggestion
                        Text(verbatim: "IDLE")
```

2024-12-08 18:22 UTC, Sjmarf commented on Mlem/Localizable.xcstrings
> +
```suggestion
```

2024-12-08 18:26 UTC, merged