Audio for Videos
mlemgroup/mlem pull request #1490
Opened 2024-12-09 17:51 UTC by EricBAndrews

# Checklist
- [x] I have read CONTRIBUTING.md
- [x] I have described what this PR contains
- [x] If this PR alters the UI, I have attached pictures/videos
- [x] This PR addresses one or more open issues that were assigned to me:
      - closes #1489 

# Pull Request Information

Enhances video handling:
- mp4s can now play audio
- Videos with audio now show a mute button on the top right
- Default mute behavior can be controlled in settings (General -> Mute Videos)
- Tapping videos now pauses them instead of stops them
- mp4s now loop

2024-12-09 21:49 UTC, Sjmarf requested changes
Nice work! 

Pressing the volume up button whilst playing a muted video unmutes the `AVQueuePlayer`, but the mute button in the UI doesn't get updated. Maybe we need to watch `player.muted` for changes and update `muted` if so? Could be tricky though if a view update doesn't get triggered when `player.muted` changes.

2024-12-09 21:49 UTC, Sjmarf commented on Mlem/App/Views/Shared/Images/Helpers/AnimationControlLayer.swift
> +                        }
*nit* this is slightly cleaner imo

```suggestion
                        .background(.ultraThinMaterial, in: .circle)
```

2024-12-09 23:20 UTC, EricBAndrews commented
Ooh, nice catch! I've added some observation code that should sort it out.

2024-12-10 11:21 UTC, Sjmarf approved these changes
LGTM! It would be nice if videos were paused once they leave the screen. If I unmute a video and scroll away, the audio keeps playing.

2024-12-11 03:41 UTC, merged