Sort Picker Improvements
mlemgroup/mlem pull request #1494
Opened 2024-12-12 11:58 UTC by Sjmarf

This is just the sort picker stuff - I haven't moved filters (e.g. "Hide read" etc) here yet.

Closes #1212
Closes #1217

If there are any unavailable sort modes, they're shown at the bottom of the list.

<img src="https://github.com/user-attachments/assets/114687f4-d7db-4a2c-a04f-37a78b750b1e" width=50%>

2024-12-13 18:29 UTC, EricBAndrews requested changes
Code looks good!

The design is very nice too--my only note is that the pin button being in a separate column feels a bit off. Some alternative ideas:
- Color/fill the icon of the selected sort instead of the checkmark; we'd need a colorblind mode alternative, since fill is not available for scaled (or we find a new icon--megaphone, maybe?)
- Shade the background of the selected sort

2024-12-13 18:29 UTC, EricBAndrews commented on Mlem/App/Views/Pages/Community/AdvancedSortView+SortButton.swift
> +                            Image(systemName: "checkmark")
*nit*

`Icons`

2024-12-13 18:29 UTC, EricBAndrews commented on Mlem/App/Views/Pages/Community/TopSortPicker.swift
> +                .fontWeight(.semibold)
Unnecessary--clear from context

2024-12-13 19:07 UTC, Sjmarf commented
> my only note is that the pin button being in a separate column feels a bit off. Some alternative ideas:

Sure, I can try those. How do you propose that the user changes whether an item is pinned or not? Via context menu? Currently, tapping the pin button toggles the pin state and tapping the sort mode itself selects it.

2024-12-13 20:28 UTC, EricBAndrews commented
Tapping the pin still seems like the way to go--we can also put it on a swipe action

2024-12-14 12:08 UTC, Sjmarf commented
How's this?

<img src="https://github.com/user-attachments/assets/fd9866cc-59f0-4035-9a75-56bc0f8fc4a1" width=30%>

I'd rather avoid using icon fill state to denote selection when we've got lots of different icons - it's much more difficult at a glance to see which is selected (to my eye, anyway).

2024-12-16 22:51 UTC, EricBAndrews approved these changes
LGTM! 🔥

2024-12-17 10:49 UTC, merged