Fullscreen Image
mlemgroup/mlem pull request #1499
Opened 2024-12-13 18:06 UTC by EricBAndrews

# Checklist
- [x] I have read CONTRIBUTING.md
- [x] I have described what this PR contains
- [x] If this PR alters the UI, I have attached pictures/videos
- [x] This PR addresses one or more open issues that were assigned to me:
      - closes #1354 

# Pull Request Information

This PR replaces the sheet-based image viewer with an overlay-based implementation. It can be swiped away either up or down.

2024-12-13 18:15 UTC, Sjmarf commented
Swipe to dismiss doesn't seem to be working for me on my physical device 🤔

2024-12-15 15:58 UTC, Sjmarf requested changes
The old `NavigationPage.imageViewer` code needs removing, assuming it isn't still being used anywhere?

2024-12-16 00:47 UTC, EricBAndrews commented
> The old NavigationPage.imageViewer code needs removing, assuming it isn't still being used anywhere?

It is still used--the overlay needs to be a `NavigationLayer` to gain access to the share menu and proxy failure popup

2024-12-16 11:16 UTC, Sjmarf approved these changes
Ah, I see 👍 LGTM!

2024-12-16 11:16 UTC, Sjmarf commented on Mlem/App/Views/Pages/ImageViewer.swift
> +//        }
Dead code?
```suggestion
```

2024-12-16 23:55 UTC, merged