Mod Mail Reports
mlemgroup/mlem pull request #1519
Opened 2024-12-17 22:44 UTC by Sjmarf

Relies on [this MlemMiddleware PR](https://github.com/mlemgroup/MlemMiddleware/pull/83).

Closes #1504. There is no content loader model yet - just some temporary code to display the first page of results. [Issue here](https://github.com/mlemgroup/mlem/issues/1520).

Reports look like this. In future the interaction bar will be customizable, but I haven't implemented this yet. [Issue here](https://github.com/mlemgroup/mlem/issues/1521).

<img src="https://github.com/user-attachments/assets/be0bfff7-f2f0-4186-b8af-d4f86ceef6bb" width=50%>

On versions prior to 0.19.4, significantly less information is included in the report responses. This makes us unable to create `Post2`/`Comment2` models on those versions, and instead we have to fallback to `Post1`/`Comment1` models.

As a result, on 0.19.3 and below the reports instead look like this:

<img src="https://github.com/user-attachments/assets/b8a8ef04-5ab9-4c70-b8ed-1fa7f0de17f9" width=50%>

The biggest downgrade here is that there is no ellipsis menu from which you can take action on the content. To do that, you have to tap on the report to open the post/comment and take action on it from there. Now, this downgrade isn't actually a limitation of the missing data - we *could* still include those ellipsis menus, but doing so would require a significant amount of work and I don't think it's worth it.

2024-12-20 17:06 UTC, EricBAndrews requested changes
Looks good overall! One minor code note, plus design discussion from Slack

2024-12-20 17:06 UTC, EricBAndrews commented on Mlem/App/Views/Root/Tabs/Feeds/Feed Comments/FeedCommentView.swift
> +        overrideIsTiled: Bool? = nil,
*nit*

It may be a little cleaner/more intuitive to simply have this be `overriddenSize: PostSize?`, rename `postSize` to `settingsPostSize`, and declare `var postSize: PostSize { overridenSize ?? postSize }` in place of the current computed `overridenSize`

2024-12-21 13:14 UTC, Sjmarf commented on Mlem/App/Views/Root/Tabs/Feeds/Feed Comments/FeedCommentView.swift
> +        overrideIsTiled: Bool? = nil,
Sure 👍

2024-12-21 13:15 UTC, Sjmarf commented
Tweaked the resolve button design pre 0.19.4.

<img src="https://github.com/user-attachments/assets/bc129162-f76a-4f2a-8785-70ddf1904d1c" width=50%>

2024-12-21 17:16 UTC, EricBAndrews approved these changes
LGTM! 🚀

2024-12-22 22:35 UTC, merged