New drag and drop
mlemgroup/mlem pull request #471
Opened 2023-08-09 22:57 UTC by Sjmarf

Adds the ability to rearrange the interaction bar widgets. There are separate layouts for the post and comment interaction bars. The Info Stack must be part of the user's layout, and there cannot be too many widgets in the stack.

The widget layouts are stored in a JSON file.

<img src="https://github.com/mlemgroup/mlem/assets/78750526/ae99ecc9-f1ce-49e8-bd4d-7cc0b9036a92" width=50%/>

2023-08-09 23:09 UTC, JakeShirley commented
FYI building this locally has a few different Swift errors on my machine.

2023-08-09 23:12 UTC, Sjmarf commented
> FYI building this locally has a few different Swift errors on my machine.

Hmmm. This is what someone said last time. I'm on the latest beta... maybe that's causing it

2023-08-09 23:54 UTC, JakeShirley commented
This is the main error I am seeing.  Extra sus that CI doesn't seem to be running on your PR either

<img width="995" alt="image" src="https://github.com/mlemgroup/mlem/assets/1000311/5dd0ebaa-c6c7-420a-97de-99a9077ef1f2">

2023-08-10 02:51 UTC, EricBAndrews commented
I'm seeing those exact same errors

XCode Version 14.3.1 (14E300c)
MacOS Ventura 13.1 (22C65)

2023-08-10 03:53 UTC, EricBAndrews commented
First and foremost: fantastic job, this is an amazing feature that is going to absolutely thrill our users.

It looks like Swift doesn't like those let declarations of view building functions. I was able to get it to run with some extremely crude and slapdash refactoring into functions, though ye be warned that this is pretty ugly code: https://github.com/EricBAndrews/mlemapp/commit/4be88591af522aeb1cd83b93092602a67565603b

Once it compiles and I can test it thoroughly I'll give it a proper review. I will say as a pre-review that `LayoutWidgetEditView.swift` is going to need a whole lot of those pyramids broken down and moved into functions anyway--there's a lot going on in there already, so if the view structure itself isn't *squeaky* clean that file is going to become a nightmare to maintain

2023-08-10 03:58 UTC, JakeShirley commented
Some small design feedback: We might want to render a preview of what the "gap" section shows (stats like post time, etc.).

2023-08-10 06:34 UTC, Sjmarf commented
> Some small design feedback: We might want to render a preview of what the "gap" section shows (stats like post time, etc.).
> 


Yeah, I considered this. However, the interaction bar as it appears in the editor is much larger than in the real thing - there is extra padding around each widget, which allows you to pick them up easier. This means that the Info Stack is much shorter than how it actually appears in the feed, and so the info stack content probably wont fit properly if I try to render it there.

2023-08-10 06:35 UTC, Sjmarf commented
> First and foremost: fantastic job, this is an amazing feature that is going to absolutely thrill our users.
> 
> 
> 
> It looks like Swift doesn't like those let declarations of view building functions. I was able to get it to run with some extremely crude and slapdash refactoring into functions, though ye be warned that this is pretty ugly code: https://github.com/EricBAndrews/mlemapp/commit/4be88591af522aeb1cd83b93092602a67565603b
> 
> 
> 
> Once it compiles and I can test it thoroughly I'll give it a proper review. I will say as a pre-review that `LayoutWidgetEditView.swift` is going to need a whole lot of those pyramids broken down and moved into functions anyway--there's a lot going on in there already, so if the view structure itself isn't *squeaky* clean that file is going to become a nightmare to maintain

Thanks, I'll refactor it 👍

2023-08-10 07:51 UTC, Sjmarf commented
It should build now (hopefully).

2023-08-10 07:58 UTC, Sjmarf commented
Ok, I've done some refactoring. It should build now, hopefully.

2023-08-10 17:03 UTC, EricBAndrews requested changes
Lots of nits, mostly focused on avoiding force unwrapping, but overall looks good!

2023-08-10 17:03 UTC, EricBAndrews commented on Mlem/Views/Tabs/Settings/Components/Views/Appearance/Shared/LayoutWidgetEditView.swift
> +                    height: widgetModel.widgetDragging!.rect!.height
*nit*

force unwraps

2023-08-10 17:36 UTC, Sjmarf commented on Mlem/Models/Settings/LayoutWidgets/LayoutWidgetCollection.swift
> +        costLimit == .infinity || totalCost(widgetDragging) <= costLimit
It's for optimisation, yeah. I'm assuming `||` works in the same way as in Python? I'll test it when I get time later.

Ie: if the first part of the `||` expression evaluates to `false`, the result cannot possibly be `true`, and so there's no need to evaluate the second part. This saves calling the `totalCost` function

2023-08-10 17:38 UTC, Sjmarf commented on Mlem/Models/Settings/LayoutWidgets/LayoutWidgetCollection.swift
> +            widgets[widget!.type] = widget
Sure 👍

2023-08-10 17:42 UTC, Sjmarf commented on Mlem/Views/Tabs/Settings/Components/Views/Appearance/Post/PostSettingsView.swift
> +                    .foregroundStyle(.pink)
I originally had it as a nav page, but changed it to a sheet for some reason that I now can't remember xD

I'll try changing it back and let you know if I encounter an issue

2023-08-10 17:45 UTC, Sjmarf commented on Mlem/Views/Tabs/Settings/Components/Views/Appearance/Shared/LayoutWidgetEditView.swift
> +        }
😎 

This is my first Swift project so I'm slowly learning all this fancy stuff as I go haha.

2023-08-10 17:58 UTC, Sjmarf commented on Mlem/Models/Settings/LayoutWidgets/LayoutWidgetCollection.swift
> +        }
Close 😉 

`items.first { $0.rect?.contains(location) ?? false }`

2023-08-10 18:35 UTC, Sjmarf commented on Mlem/Models/Settings/LayoutWidgets/LayoutWidgetCollection.swift
> +        costLimit == .infinity || totalCost(widgetDragging) <= costLimit
Yep, that is indeed how it works

2023-08-10 19:11 UTC, Sjmarf commented on Mlem/Views/Tabs/Settings/Components/Views/Appearance/Post/PostSettingsView.swift
> +                    .foregroundStyle(.pink)
I got it working 👍

2023-08-10 19:32 UTC, merged