#461 collapse post content
mlemgroup/mlem pull request #491
Opened 2023-08-12 00:13 UTC by boscojwho

# Checklist
- [ ] I have read [CONTRIBUTING.md](./CONTRIBUTING.md)
- [ ] I have described what this PR contains
- [ ] This PR addresses one or more open issues that were assigned to me:
      - *list issue(s) here*
- [ ] If this PR alters the UI, I have attached pictures/videos

# Pull Request Information

## About this Pull Request
Adds ability to minimize (collapse) a post's content when viewing as expanded post.
- Tested in light and dark modes.
- Tested in right-to-left language mode.
- Accessibility support.

## Screenshots and Videos
https://github.com/mlemgroup/mlem/assets/2549615/f0dbc7f5-b266-43ee-8932-70962ae255cb
https://github.com/mlemgroup/mlem/assets/2549615/df4b1a8e-1b3b-47d6-969e-707544e56d05

## Additional Context
Not so sure about the accessibility hint/label.

2023-08-12 19:57 UTC, EricBAndrews requested changes
A couple nits and minor cleanliness/refactoring comments but looks good overall!

2023-08-12 19:57 UTC, EricBAndrews commented on Mlem/Views/Shared/Posts/Post Sizes/Large Post.swift
> +        }
*nit*

2-case switch statements should be done as a simple if/else or ternary

2023-08-12 19:57 UTC, EricBAndrews commented on Mlem/Views/Shared/Posts/Post Sizes/Large Post.swift
> +        }
*nit*

See above re: 2-case switch

2023-08-12 19:57 UTC, EricBAndrews commented on Mlem/Views/Shared/Posts/Post Sizes/Large Post.swift
> +        }
*nit*

2-case switch

2023-08-12 19:57 UTC, EricBAndrews commented on Mlem/Views/Shared/Posts/Post Sizes/Large Post.swift
> +            Color.clear
*nit*

2-case switch

2023-08-12 19:57 UTC, EricBAndrews commented on Mlem/Views/Shared/Posts/Post Sizes/Large Post.swift
> +            .accessibilityHint("Expands post content.")
🙏 kudos for accessibility tags

2023-08-12 19:57 UTC, EricBAndrews commented on Mlem/Views/Shared/Posts/Post Sizes/Large Post.swift
> +        }
These can all be defined on the `LayoutMode` enum itself, then just used as `layoutMode.lineLimit` and `layoutMode.maxHeight`

2023-08-13 19:31 UTC, EricBAndrews approved these changes

2023-08-13 19:31 UTC, merged

2023-08-13 20:06 UTC, fer0n commented
@boscojwho I'm assuming it's not on purpose that the markdown in feed (large post size) is now no longer truncated?

2023-08-13 22:30 UTC, EricBAndrews commented
I just noticed that as well, have a PR incoming to fix it

2023-08-15 02:14 UTC, boscojwho commented
> @boscojwho I'm assuming it's not on purpose that the markdown in feed (large post size) is now no longer truncated?

Should be fixed in #501

2023-08-15 08:41 UTC, fer0n commented
It's already fixed, yes. I also made some changes to the markdown preview which would've also taken care of it anyways :)