Improved Search
mlemgroup/mlem pull request #566
Opened 2023-09-02 19:37 UTC by Sjmarf

Changed the search tab to allow searching of users and posts. This isn't quite done yet, but I wanted to gather some feedback on what I've got so far.

<hr>

<img src="https://github.com/mlemgroup/mlem/assets/78750526/cc7edfea-1609-4742-a67c-f8fc7cdf5adc" width=32%\>

<img src="https://github.com/mlemgroup/mlem/assets/78750526/d72b8499-afb3-4f4b-b60f-68dcfcfe1df4" width=32%\>

<img src="https://github.com/mlemgroup/mlem/assets/78750526/1acc5a9d-5bf6-499e-9148-84abdcbbe6cf" width=32%\>

<hr>

The time results take to load seems to vary; sometimes it can be a little slow. If anyone knows of a way I can speed this up (I'm not too familiar with async stuff), that would be greatly appreciated :)

Things I still need to do:
- Right now, only 50 results are loaded and it won't load more when you scroll down.
- Reimplement recent searches.
- Fix a couple of bugs.
- Searching comments (may not be in the initial PR, we'll see)
- Searching instances (definitely won't be in this PR, we need an instance screen first anyway)

2023-09-03 02:45 UTC, EricBAndrews requested changes
Bunch of dead code that can be removed. It would also be nice for maintainability to have a couple comments, especially in the model section

2023-09-03 02:45 UTC, EricBAndrews commented on Mlem/Views/Tabs/Search/Components/SearchSectionHeaderView.swift
> +//            }
Bunch of dead code in here

2023-09-03 02:45 UTC, EricBAndrews commented on Mlem/Views/Tabs/Search/SearchModel.swift
> +class SearchModel: ObservableObject {
*nit*

This is a model, so it shouldn't live under the `Views` tree

2023-09-03 02:45 UTC, EricBAndrews commented on Mlem/Views/Tabs/Search/SearchView.swift
> +                // .navigationBarColor()
*nit*

Dead code? Forgot to re-enable?

2023-09-03 02:45 UTC, EricBAndrews commented on Mlem/Views/Tabs/Search/SearchView.swift
> +                    LazyVStack(spacing: 10) { // pinnedViews: [.sectionHeaders]
*nit*

Dead code

2023-09-03 02:45 UTC, EricBAndrews commented on Mlem/Views/Tabs/Search/SearchView.swift
> +                }
Dead code

2023-09-03 02:45 UTC, EricBAndrews commented on Mlem/Views/Tabs/Search/SearchView.swift
> +                    }
Dead code

2023-09-03 02:50 UTC, EricBAndrews commented
Scrolling performance on searches is also pretty wonky. If you get a bunch of results and scroll, it gets very inconsistent in what posts get rendered--you can scroll for a long time down, then back up super fast.

Overall looks really good though!

2023-09-03 07:56 UTC, Sjmarf commented
> Bunch of dead code that can be removed.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

Yep, I'm aware :) As I mentioned, there's still some stuff I needed to fix. Some of that is code that sort-of works for loading more pages, but is too buggy atm.

> It would also be nice for maintainability to have a couple comments, especially in the model section 

Sure 👍

2023-09-03 07:58 UTC, Sjmarf commented
> If you get a bunch of results and scroll, it gets very inconsistent in what posts get rendered--you can scroll for a long time down, then back up super fast.

Yeah. I have a feeling this is caused by the fancy highlighted-text, which does its calculations using .onAppear. Maybe it's not worth it.

2023-09-03 17:38 UTC, Sjmarf commented
> I haven't had time to review this yet but I notice in the description there is mention of searching instances - would instance search make sense in this area?
> 
> The user has selected an instance by this stage, we are looking to add some search functionality on instances but I believe this would be restricted to the onboarding / guest journeys before entering the app at which point they have access to _this_ search which is using the current instances API to perform searches for communities/posts/users/comments etc?

Of course, it's the least likely category to want to search. It would be all the way at the bottom below every other category. When we implement instance pages, it would make sense to include information about how many users the instance has, as well as potentially an uptime graph if we can find a third-party API for it. If we end up having functionality like that, it's reasonable that some people might want to see this information for instances that they aren't a part of. Hence the search-ability. But yeah, not a priority.

2023-09-04 07:04 UTC, Sjmarf commented
> I couldn't picture what would happen when the user tapped an instance result, but general information about it makes sense... once guest mode is in we _could_ let people enter guest mode for the instance from that page, too 😱 

Indeed! Maybe a "sign up" button could go on the instance page if the user is in guest mode too?

The instance sidebar is another bit of information that we don't currently display anywhere, so obviously that'd go in the instance page too. Also an admin list

2023-09-24 13:32 UTC, Sjmarf commented
Will be replaced by an upcoming PR

2023-09-24 13:32 UTC, closed without merging