fix - limit instance list and add search
mlemgroup/mlem pull request #618
Opened 2023-09-17 19:47 UTC by mormaer

# Checklist
- [x] I have read [CONTRIBUTING.md](./CONTRIBUTING.md)
- [x] I have described what this PR contains
- [x] This PR addresses one or more open issues that were assigned to me:
      - Related to #534 
- [x] If this PR alters the UI, I have attached pictures/videos

# Pull Request Information

## About this Pull Request
This PR limits the number of instances we display during onboarding, and adds basic search functionality to allow the user to find instances which are not shown in the initial 30 that we currently limit to.

## Screenshots and Videos
| VIDEO |
| --- |
| <video src="https://github.com/mlemgroup/mlem/assets/5231793/aedb2515-36bf-49d0-8045-b7dbe1b7bb51" >

## Additional Context
This PR is built on top of #613

2023-09-18 19:11 UTC, EricBAndrews requested changes

2023-09-18 19:11 UTC, EricBAndrews commented on Mlem/Views/Shared/Accounts/Instance Picker View.swift
> +            .filter(\.newUsers) // restrict the list to instances who are accepting new users
While we're filtering, can we exclude NSFW instances from the default list as well? As far as I can tell the only two in the list are lemmynsfw and pornlemmy--both of them conveniently have "nsfw" in their version number, so we could also use that as a filter criterion.

2023-09-20 03:20 UTC, boscojwho approved these changes
✅ works as expected on Home button/Home indicator devices, and iOS 17.

2023-09-22 21:56 UTC, EricBAndrews approved these changes

2023-09-22 21:56 UTC, merged