Better 'no posts to be found' message
mlemgroup/mlem pull request #714
Opened 2023-10-10 21:59 UTC by Sjmarf

Centered the loading graphic and replace "no posts to be found" message (see images).
<p float="left">
<img src="https://github.com/mlemgroup/mlem/assets/78750526/37913fad-3fa9-40cd-bd24-7f105aff7235" width=40%>
<img src="https://github.com/mlemgroup/mlem/assets/78750526/e101fcbd-543a-4626-b844-5e22f856abfe" width=40%>
</p>
<p float="left">
<img src="https://github.com/mlemgroup/mlem/assets/78750526/fd6fcaa2-b3ad-477c-adc3-17d89920c418" width=40%>
<img src="https://github.com/mlemgroup/mlem/assets/78750526/0ce32013-1022-4b5a-b4a9-0f9bd67340a1" width=40%>
</p>

2023-10-11 21:23 UTC, Sjmarf commented
Added the fancy error-message from `ExpandedPostView` too
<img src="https://github.com/mlemgroup/mlem/assets/78750526/3dd3d9c0-3e40-4191-b4b0-dce29b89e5b9" width=30%>

2023-10-14 19:26 UTC, Sjmarf commented
In future we could do something similar for the inbox tab, offering a button to show all messages if the user is only viewing unread messages

2023-10-26 16:35 UTC, EricBAndrews requested changes
Nice! Minor wording comment, but fantastic work as always

2023-10-26 16:35 UTC, EricBAndrews commented on Mlem/Views/Tabs/Feeds/Components/NoPostsView.swift
> +                        )
Could be more concise:

`\(unreadItems) read post \(unreadItems == 1 ? " has" : "s have") been hidden`

Along with the "show read," I think it's clear enough what's going on

2023-10-28 02:52 UTC, EricBAndrews approved these changes

2023-10-28 08:06 UTC, merged