Fix `flowDidChange` being called extraneously
mlemgroup/mlem pull request #850
Opened 2024-01-11 21:53 UTC by Sjmarf

`flowDidChange` was called via `onAppear` on the `Window` view. This caused `onAppear` to be called when navigating back from an external link. 

This _might_ be related to the app store review about having to re-authenticate when navigating back from an external link?

It might also be related to the error haptic that I've been getting when navigating back from a link, though I'm not sure because I can't reproduce that bug at the moment. It might be dependent on internet speed or something, because I was able to reproduce it consistently yesterday and nothing's changed since then.

2024-01-15 22:40 UTC, EricBAndrews requested changes
Looks good! Maybe leftover test print?

2024-01-15 22:40 UTC, EricBAndrews commented on Mlem/Window.swift
> +        print("FLOW CHANGE")
Intentional?

2024-01-16 11:26 UTC, Sjmarf commented on Mlem/Window.swift
> +        print("FLOW CHANGE")
Removed 👍

2024-01-25 23:33 UTC, EricBAndrews approved these changes
Nice 👍

2024-01-25 23:33 UTC, merged