Search Instances
mlemgroup/mlem pull request #873
Opened 2024-01-22 17:11 UTC by Sjmarf

> [!important]
> This PR is built ontop of #869 and #856. Drafting until those are in.

## Instance Search

Adds an "instances" tab to search. When the app opens, the instance list is downloaded from https://github.com/mlemgroup/mlem-stats. That repo has a GH action set up to refresh the data every 24 hours. So if an instance changes their avatar or version number, it could take 48 hours for it to be updated in Mlem (lemmyverse's 24h maximum, followed by our 24h maximum). Instances that have a negative score, have less than 20 users or are censured on fediseer are excluded. This cuts the list down from 855 to 160 instances.

<img src="https://github.com/mlemgroup/mlem/assets/78750526/5d1578a0-b809-465a-80a3-d3a897b29c6e" width=50%>

2024-01-31 21:51 UTC, EricBAndrews requested changes
Looks good! A couple nits, and I also noticed some inconsistent behavior around searching:

https://github.com/mlemgroup/mlem/assets/44140166/2e341ec6-c495-4d07-b102-e5c1265c1f60

It's minor enough that I don't see a need to hold up the merge to resolve it, but if we merge with this behavior still present it's worth opening an issue.

2024-01-31 21:51 UTC, EricBAndrews commented on Mlem/Views/Tabs/Search/SearchResultsView.swift
> +//            .animation(.default, value: contentTracker.isLoading)
Dead code?

2024-01-31 21:51 UTC, EricBAndrews commented on Mlem/Views/Tabs/Search/SearchView.swift
>              .onAppear {
*nit*

This can be a `.task` since it's all async

2024-01-31 22:04 UTC, Sjmarf commented
Nice catch! Should be fixed 👍

2024-02-01 00:34 UTC, EricBAndrews approved these changes
Nice! 🚀

2024-02-01 06:30 UTC, merged