Render pinned posts in compact mode if already read.
mlemgroup/mlem pull request #948
Opened 2024-02-20 20:46 UTC by boscojwho

# Checklist
- [x] I have read CONTRIBUTING.md
- [x] I have described what this PR contains
- [x] If this PR alters the UI, I have attached pictures/videos
- [x] This PR addresses one or more open issues that were assigned to me:
      - closes #930 

# Pull Request Information

## About this Pull Request
Render pinned posts (`FeedPost`) in compact mode if already read.

## Screenshots and Videos
<img src="https://github.com/mlemgroup/mlem/assets/2549615/37ff0fb2-4144-47d2-9646-f78ec64ed218" width="320">

2024-02-20 21:32 UTC, EricBAndrews commented
What do we think about enabling this only within a community? It works really nicely when the pinned posts are all collected at the top but it's a little weird to come across a random compact post when scrolling through an aggregate feed

2024-02-20 21:33 UTC, EricBAndrews requested changes
Pending above comment

2024-02-20 22:07 UTC, boscojwho commented
> What do we think about enabling this only within a community? It works really nicely when the pinned posts are all collected at the top but it's a little weird to come across a random compact post when scrolling through an aggregate feed

Oh totally yes, didn't think about pinned posts showing up in aggregate feed, will look into it.

2024-02-20 22:27 UTC, boscojwho commented
> What do we think about enabling this only within a community? It works really nicely when the pinned posts are all collected at the top but it's a little weird to come across a random compact post when scrolling through an aggregate feed

Added `guard let community, postTracker?.feedType == .community(community)` to only render pinned posts as compact in community feeds.

2024-02-20 22:47 UTC, EricBAndrews requested changes

2024-02-20 22:47 UTC, EricBAndrews commented on Mlem/Views/Shared/Posts/Feed Post.swift
> +        guard let community, postTracker?.feedType == .community(community) else {
Something's funky with this logic--it's not consistently working when I test locally. This should do the trick:
```suggestion
        guard case .community = postTracker?.feedType else {
```

2024-04-23 23:13 UTC, closed without merging

2024-04-23 23:13 UTC, EricBAndrews commented
Stale as of #1046