Mod/Admin Actions for Comments
mlemgroup/mlem pull request #987
Opened 2024-03-22 15:45 UTC by Sjmarf

2024-03-23 16:04 UTC, EricBAndrews commented
The sheet isn't dismissing properly--the action performs, but the sheet remains

https://github.com/mlemgroup/mlem/assets/44140166/d26b640d-40f0-4ebb-82a4-de854a8a418b

2024-03-23 16:07 UTC, EricBAndrews requested changes

2024-03-23 16:20 UTC, Sjmarf commented on Mlem/API/Requests/Comment/PurgeCommentRequest.swift
> +    }
Nice catch! It was missing from some of the others, too

2024-03-24 15:51 UTC, EricBAndrews approved these changes
LGTM!

2024-03-24 16:09 UTC, merged